import { NextFunction, Request, RequestHandler, Response } from 'express';

// try catch all exceptions in one place
const catchAsync = (fn: RequestHandler) => {
  return (req: Request, res: Response, next: NextFunction) => {
    Promise.resolve(fn(req, res, next)).catch((err) => next(err));
  };
};

export default catchAsync;
